### PR TITLE
Refactor to improve readability

### PR DESCRIPTION
**Pull request by torrocus**
The goal of this PR is to improve readability. The functionality is the same.
- [x] Key collections are constants.
- [x] Remove rescue exceptions. Instead, the logical operator and default value were used.
- [x] Array operations have replaced Set operations, because they are faster.
- [x] The initializer has been divided into smaller methods.

Finally got rid of `.rubocop_todo.yml`.

BTW I increment the gem version. The version 1.3.1 on rubygems is not working properly, but the code on GitHub is correct. I suspect that someone was build a gem before pull changes from repo.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Couple of stuff I'd like changed here, @torrocus:
- Please remove the change to `version.rb`. That'll be updated when a maintainer cuts the new release.
- Please change the constants to *private* (as simple as `private_constant :FOO, :BAR` after they're defined), mainly because I don't see the need to expose them as *public*

Lastly, something about the use of `proc.call` doesn't seem fine to me (*personal nit*). Could it be refined further?

**Comment by torrocus** [comment]
- [x] I removed the change in `version.rb`
    This change resulted from the fact that version 1.3.1 on rubygems is not working properly. It would be great if the maintainer did a new build to rubygems.
- [x] I changed the constants to private. Good point.
- [x] I moved `Jekyll::External.require_with_graceful_fail "commonmarker"` before definitions of constants.
      However, this require worked because in `html_renderer.rb` is also require it. I'm thinking about moving this over `require_relative "jekyll-commonmark/html_renderer"` and removing it from the file `html_renderer.rb`. 
      What do you think, @ashmaroli?

**Comment by torrocus** [comment]
I changed to call `Jekyll::External.require_with_graceful_fail "commonmarker"` only in one place. This seems reasonable.

**Comment by ashmaroli** [comment]
@torrocus I missed it in the first pass but `VALID_OPTIONS = (PARSE_KEYS + RENDER_KEYS).uniq` could be shortened to:
```ruby
VALID_OPTIONS = PARSE_KEYS | RENDER_KEYS
```
But no worries, since this has an approval, I'll make the changes in a future PR that refactors the logic around `:prepare` and `:validate`.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Pull request merged**
