### PR TITLE
Set up Continuous Integration via GH Actions

### PR DESCRIPTION
**Pull request by ashmaroli**
- Test on Ruby versions with 2.6, 2.7 and 3.0 w/ Jekyll 4 and on Ruby 2.6 w/ Jekyll 3.9
- Delete TravisCI config
- Lock to `rubocop-jekyll-0.12.x`.

### CODE REVIEW

**Review by mattr- — APPROVED** [review]
:shipit:

**Comment by ashmaroli** [comment]
Wonder why the workflow did not get triggered.. :thinking: *It should have..*

**Comment by mattr-** [comment]
Perhaps because it came from a fork? There's rules around what actions get kicked off when the branch comes from a fork and this could be hitting one of those.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
There were couple of errors in the workflow file.
Fixed in 64e4fd2 and 4ef7db2.

**Pull request merged**
