### PR TITLE
Test plugin on Windows

### LINKED ISSUE #11: Test on Windows
We want to make sure that this plugin works well on Windows, especially if it could potentially become the Jekyll default.

Let's set up CI to test on Windows :+1:

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves #11 

This adds configuration for AppVeyor and an SVG Badge to the Readme.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Looks like AppVeyor has not been activated for this repo..

**Comment by pathawks** [comment]
> Looks like AppVeyor has not been activated for this repo.

✅ Done

**Comment by pathawks** [comment]
@jekyllbot: merge +dev

**Comment by pathawks** [comment]
Oh cool! I didn't think that would work.

Thanks @parkr 😍

**Pull request merged**
